---
- name: 'persist iptables'
  shell: iptables-save > /etc/iptables/rules.v4 && ip6tables-save > /etc/iptables/rules.v6
  notify: 'restart networking'

- name: 'restart networking'
  service:
    name: networking
    state: restarted

- name: 'restart fail2ban'
  service:
    name: fail2ban
    state: restarted
